
version: 0.2
phases:
  install:
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
